image: gitpod/workspace-full
tasks:
  - name: shell
    command: echo "Hello"
  - name: setup
    init: .gitpod/setup.sh
    command: .gitpod/setup.sh
  - name: k3s
    command: .gitpod/run/qemu.sh
ports:
  - port: 32080
    visibility: private
    description: K3s HTTP Ingress
  - port: 2222
    visibility: private
    description: K3s SSH
    onOpen: ignore
  - port: 6443
    visibility: private
    description: K3s API
    onOpen: ignore
